import { Article, Category, MarketRate, Poetry, PrayerTime } from '@/types';

export const mockCategories: Category[] = [
  { id: 1, name_urdu: 'صفحہ اول', name_english: 'Home', slug: 'home', color: '#004b23' },
  { id: 2, name_urdu: 'پاکستان', name_english: 'Pakistan', slug: 'pakistan', color: '#004b23' },
  { id: 3, name_urdu: 'بین الاقوامی', name_english: 'World', slug: 'world', color: '#1e3a8a' },
  { id: 4, name_urdu: 'تجارت و معیشت', name_english: 'Business', slug: 'business', color: '#065f46' },
  { id: 5, name_urdu: 'کھیل و کرکٹ', name_english: 'Sports', slug: 'sports', color: '#9a3412' },
  { id: 6, name_urdu: 'شوبز و تفریح', name_english: 'Showbiz', slug: 'showbiz', color: '#831843' },
  { id: 7, name_urdu: 'ٹیکنالوجی', name_english: 'Technology', slug: 'technology', color: '#4c1d95' },
  { id: 8, name_urdu: 'اسلامی دنیا', name_english: 'Islamic', slug: 'islamic', color: '#14532d' },
  { id: 9, name_urdu: 'اردو شاعری', name_english: 'Poetry', slug: 'poetry', color: '#701a75' },
];

export const mockMarketRates: MarketRate[] = [
  { id: 1, rate_type: 'forex', symbol: 'USD/PKR', title_urdu: 'امریکی ڈالر', buying_price: 278.50, selling_price: 280.20, change_direction: 'up', change_amount: 0.35, change_percentage: 0.12, rate_date: '2026-08-31' },
  { id: 2, rate_type: 'forex', symbol: 'SAR/PKR', title_urdu: 'سعودی ریال', buying_price: 74.20, selling_price: 74.85, change_direction: 'down', change_amount: 0.10, change_percentage: 0.13, rate_date: '2026-08-31' },
  { id: 3, rate_type: 'forex', symbol: 'AED/PKR', title_urdu: 'اماراتی درہم', buying_price: 75.80, selling_price: 76.40, change_direction: 'up', change_amount: 0.05, change_percentage: 0.06, rate_date: '2026-08-31' },
  { id: 4, rate_type: 'forex', symbol: 'GBP/PKR', title_urdu: 'برطانوی پاؤنڈ', buying_price: 355.10, selling_price: 358.50, change_direction: 'up', change_amount: 1.20, change_percentage: 0.34, rate_date: '2026-08-31' },
  { id: 5, rate_type: 'forex', symbol: 'EUR/PKR', title_urdu: 'یورو', buying_price: 302.40, selling_price: 305.80, change_direction: 'down', change_amount: 0.45, change_percentage: 0.15, rate_date: '2026-08-31' },
  { id: 6, rate_type: 'gold', symbol: '24K_TOLA', title_urdu: 'سونا 24 کیراٹ (فی تولہ)', buying_price: 242500, selling_price: 243200, change_direction: 'up', change_amount: 1500, change_percentage: 0.62, rate_date: '2026-08-31' },
  { id: 7, rate_type: 'gold', symbol: '24K_10G', title_urdu: 'سونا 24 کیراٹ (10 گرام)', buying_price: 207905, selling_price: 208500, change_direction: 'up', change_amount: 1280, change_percentage: 0.61, rate_date: '2026-08-31' },
];

export const mockPrayerTimes: PrayerTime[] = [
  { id: 1, city_name_urdu: 'کراچی', city_name_english: 'Karachi', fajr: '05:12 AM', sunrise: '06:28 AM', dhuhr: '12:35 PM', asr: '04:02 PM', maghrib: '06:42 PM', isha: '07:58 PM', date: '2026-08-31' },
  { id: 2, city_name_urdu: 'لاہور', city_name_english: 'Lahore', fajr: '04:52 AM', sunrise: '06:14 AM', dhuhr: '12:20 PM', asr: '03:52 PM', maghrib: '06:26 PM', isha: '07:48 PM', date: '2026-08-31' },
  { id: 3, city_name_urdu: 'اسلام آباد', city_name_english: 'Islamabad', fajr: '04:50 AM', sunrise: '06:15 AM', dhuhr: '12:22 PM', asr: '03:56 PM', maghrib: '06:29 PM', isha: '07:54 PM', date: '2026-08-31' },
  { id: 4, city_name_urdu: 'پشاور', city_name_english: 'Peshawar', fajr: '04:55 AM', sunrise: '06:20 AM', dhuhr: '12:26 PM', asr: '04:00 PM', maghrib: '06:33 PM', isha: '07:58 PM', date: '2026-08-31' },
  { id: 5, city_name_urdu: 'کوئٹہ', city_name_english: 'Quetta', fajr: '05:18 AM', sunrise: '06:38 AM', dhuhr: '12:44 PM', asr: '04:16 PM', maghrib: '06:50 PM', isha: '08:10 PM', date: '2026-08-31' },
];

export const mockBreakingNews: string[] = [
  'وفاقی کابینہ کا اہم اجلاس، معاشی اصلاحات کے پیکج کی منظوری دے دی گئی',
  'پاکستانی روپیہ ڈالر کے مقابلے میں مستحکم، اسٹاک ایکسچینج میں ریکارڈ 900 پوائنٹس کا اضافہ',
  'قومی کرکٹ ٹیم کا اینٹیگا ٹیسٹ کے لیے سکواڈ کا اعلان، شاہین آفریدی کی واپسی',
  'سی پی سی کی توسیع: نئے صنعتی زونز کی تعمیر کے لیے 3 ارب ڈالر کی سرمایہ کاری کی منظوری',
  'وزارت سائنس و ٹیکنالوجی کا پہلے ملکی مصنوعی ذہانت کے ڈیٹا سینٹر کے قیام کا اعلان',
];

export const mockArticles: Article[] = [
  {
    id: 101,
    category_id: 2,
    category: mockCategories[1],
    author_name: 'عامر محمود',
    title_urdu: 'معاشی بحالی کا نیا سفر: اسٹیٹ بینک کا شرح سود میں بڑی کٹوتی کا اشارہ',
    slug_urdu: 'economic-recovery-state-bank-interest-rate-cut',
    slug_roman: 'economic-recovery-state-bank-interest-rate-cut',
    summary_urdu: 'اسٹیٹ بینک آف پاکستان نے افراط زر میں ریکارڈ کمی کے بعد شرح سود میں ممکنہ 200 بیسس پوائنٹس کی کٹوتی کا اشارہ دیا ہے۔',
    content_urdu: `<p>اسلام آباد (باخبر رپورٹ): اسٹیٹ بینک آف پاکستان کے ترجمان کے مطابق مسلسل چوتھے ماہ شرحِ تورم (انفلیشن) میں ریکارڈ کمی دیکھی گئی ہے۔ معاشی ماہرین کا ماننا ہے کہ اس سے ملکی صنعتوں کو نیا تحرک ملے گا اور روزگار کے نئے مواقع پیدا ہوں گے۔</p><p>وزارتِ خزانہ کے حکام نے بتایا کہ بنیادی اشیائے ضروریہ کی قیمتوں میں استحکام اور روپیہ کی قدر میں بہتری کے سبب اقتصادی اشاریے مضبوط ہو رہے ہیں۔</p>`,
    featured_image: 'https://images.unsplash.com/photo-1611974789855-9c2a0a7236a3?auto=format&fit=crop&w=1200&q=80',
    image_caption_urdu: 'اسٹیٹ بینک آف پاکستان اسلام آباد عمارت',
    view_count: 14200,
    is_breaking: true,
    is_featured: true,
    is_trending: true,
    status: 'published',
    published_at: '2026-08-31T14:30:00Z',
    tags: ['معیشت', 'اسٹیٹ بینک', 'پاکستان'],
  },
  {
    id: 102,
    category_id: 5,
    category: mockCategories[4],
    author_name: 'طارق سعید',
    title_urdu: 'ایشیا کپ 2026: قومی کرکٹ ٹیم کا بھارت کے خلاف سنسنی خیز مقابلے کے لیے زبردست مشقیں',
    slug_urdu: 'asia-cup-2026-pakistan-vs-india-prep',
    slug_roman: 'asia-cup-2026-pakistan-vs-india-prep',
    summary_urdu: 'قومی ٹیم نے قذافی اسٹیڈیم میں فلڈ لائٹس کے نیچے تین گھنٹے کا بھرپور پریکٹس سیشن مکمل کیا۔',
    content_urdu: `<p>لاہور: پاکستان اور بھارت کے درمیان سنسنی خیز مقابلے سے قبل قومی کرکٹ ٹیم کے کپتان نے پریس کانفرنس کرتے ہوئے کہا کہ ٹیم کی فارم اور مورال انتہائی بلند ہے اور وہ میدان میں بہترین کارکردگی کا مظاہرہ کریں گے۔</p>`,
    featured_image: 'https://images.unsplash.com/photo-1540747913346-19e32dc3e97e?auto=format&fit=crop&w=800&q=80',
    view_count: 9800,
    is_breaking: false,
    is_featured: true,
    is_trending: true,
    status: 'published',
    published_at: '2026-08-31T12:15:00Z',
    tags: ['کرکٹ', 'ایشیا کپ', 'پاکستان'],
  },
  {
    id: 103,
    category_id: 7,
    category: mockCategories[6],
    author_name: 'ذیشان ملک',
    title_urdu: 'مصنوعی ذہانت اور جدید کلاؤڈ سسٹمز: پاکستان کی آئی ٹی برآمدات 4 ارب ڈالر سے تجاوز کر گئیں',
    slug_urdu: 'ai-and-cloud-systems-pakistan-it-exports',
    slug_roman: 'ai-and-cloud-systems-pakistan-it-exports',
    summary_urdu: 'پاکستان سوفٹ ویئر ہاؤسز ایسوسی ایشن (Pasha) کی رپورٹ کے مطابق پاکستانی ڈیولپرز اور فری لانسرز عالمی سطح پر اہم کردار ادا کر رہے ہیں۔',
    content_urdu: `<p>کراچی: وزارتِ آئی ٹی کے مطابق رواں مالی سال میں پاکستان کی سافٹ ویئر برآمدات نے تاریخی ریکارڈ قائم کیا ہے۔ جدید AI ماڈلز اور کلاؤڈ انفراسٹرکچر میں مقامی ٹیلنٹ کی مانگ دنیا بھر میں تیزی سے بڑھ رہی ہے۔</p>`,
    featured_image: 'https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&w=800&q=80',
    view_count: 7600,
    is_breaking: false,
    is_featured: true,
    is_trending: false,
    status: 'published',
    published_at: '2026-08-31T10:00:00Z',
    tags: ['آئی ٹی', 'ٹیکنالوجی', 'اے آئی'],
  },
  {
    id: 104,
    category_id: 3,
    category: mockCategories[2],
    author_name: 'سید فیضان',
    title_urdu: 'اقوام متحدہ کی سلامتی کونسل کا ماحول و موسمیاتی تبدیلی پر ہنگامی اجلاس',
    slug_urdu: 'un-security-council-climate-change-meeting',
    slug_roman: 'un-security-council-climate-change-meeting',
    summary_urdu: 'عالمی قائدین نے ترقی پذیر ممالک کے لیے 100 ارب ڈالر کے ایمرجنسی ماحولیاتی فنڈ کی فوری منتقلی کا مطالبہ کر دیا۔',
    content_urdu: `<p>نیویارک: اقوام متحدہ کے ہیڈ کوارٹر میں منعقدہ اجلاس میں پاکستان کے مستقل مندوب نے ترقی پذیر ممالک میں موسمیاتی اثرات پر تفصیلی رپورٹ پیش کی اور عالمی برادری سے تعاون پر زور دیا۔</p>`,
    featured_image: 'https://images.unsplash.com/photo-1541872703-74c5e44368f9?auto=format&fit=crop&w=800&q=80',
    view_count: 5400,
    is_breaking: false,
    is_featured: true,
    is_trending: false,
    status: 'published',
    published_at: '2026-08-31T09:30:00Z',
    tags: ['اقوام متحدہ', 'بین الاقوامی', 'موسمیات'],
  },
  {
    id: 105,
    category_id: 6,
    category: mockCategories[5],
    author_name: 'نادیہ خان',
    title_urdu: 'پاکستان فلم فیسٹیول 2026: بین الاقوامی ایوارڈز میں دو اردو فلموں کی نامزدگی',
    slug_urdu: 'pakistan-film-festival-nominations',
    slug_roman: 'pakistan-film-festival-nominations',
    summary_urdu: 'عالمی معیار کے اسکرپٹ اور ڈائریکشن نے عالمی نقادوں کے دل جیت لیے۔',
    content_urdu: `<p>کراچی: پاکستانی سینیما کے احیاء کی سفر میں ایک اور سنگِ میل طے ہو گیا۔ دو نئی اردو فیچر فلمیں عالمی فلم فیسٹیول کے مقابلے میں شامل کر لی گئی ہیں۔</p>`,
    featured_image: 'https://images.unsplash.com/photo-1489599849927-2ee91cede3ba?auto=format&fit=crop&w=800&q=80',
    view_count: 8100,
    is_breaking: false,
    is_featured: false,
    is_trending: true,
    status: 'published',
    published_at: '2026-08-31T08:20:00Z',
    tags: ['شوبز', 'فلم', 'ثقافت'],
  },
  {
    id: 106,
    category_id: 8,
    category: mockCategories[7],
    author_name: 'حافظ رضوان',
    title_urdu: 'ماہِ ربیع الاول کی روح پرور تیاریاں: ملک بھر میں مسجدوں کو چراغاں کر دیا گیا',
    slug_urdu: 'moulud-un-nabi-preparations-pakistan',
    slug_roman: 'moulud-un-nabi-preparations-pakistan',
    summary_urdu: 'اسلام آباد، لاہور اور کراچی سمیت تمام چھوٹے بڑے شہروں میں محافلِ نعت کا اہتمام۔',
    content_urdu: `<p>اسلام آباد: ملک بھر میں مذہبی عقیدت و احترام کا اظہار کیا جا رہا ہے۔ اہم شاہراہوں اور عمارتوں کو دلکش برقی قمقموں سے سجا دیا گیا ہے۔</p>`,
    featured_image: 'https://images.unsplash.com/photo-1519817650390-64a93db51149?auto=format&fit=crop&w=800&q=80',
    view_count: 11200,
    is_breaking: false,
    is_featured: false,
    is_trending: true,
    status: 'published',
    published_at: '2026-08-31T07:10:00Z',
    tags: ['اسلامی', 'پاکستان', 'محفل'],
  },
];

export const mockPoetry: Poetry[] = [
  {
    id: 1,
    poet_name_urdu: 'علامہ محمد اقبال',
    poet_name_english: 'Allama Iqbal',
    title_urdu: 'سودائی و عقل',
    slug: 'sudai-o-aql-iqbal',
    type: 'ghazal',
    views: 18500,
    is_featured: true,
    stanzas: [
      { misra_1: 'ترے عشق کی انتہا چاہتا ہوں', misra_2: 'میری سادگی دیکھ کیا چاہتا ہوں' },
      { misra_1: 'بھری بزم میں راز کی بات کہہ دی', misra_2: 'بڑا بے ادب ہوں سزا چاہتا ہوں' },
      { misra_1: 'بھروسہ نہیں ہے ریاضِ جہاں کا', misra_2: 'ترے در کی دائمی پناہ چاہتا ہوں' },
    ],
  },
  {
    id: 2,
    poet_name_urdu: 'میر تقی میر',
    poet_name_english: 'Mir Taqi Mir',
    title_urdu: 'ہستی اپنی حباب کی سی ہے',
    slug: 'hasti-apni-hubab-ki-si-hai',
    type: 'ghazal',
    views: 14200,
    is_featured: true,
    stanzas: [
      { misra_1: 'ہستی اپنی حباب کی سی ہے', misra_2: 'یہ نمائش سراب کی سی ہے' },
      { misra_1: 'نازکی اس کے لب کی کیا کہئے', misra_2: 'پنکھڑی اک گلاب کی سی ہے' },
      { misra_1: 'بار بار اس کے در پہ جاتا ہوں', misra_2: 'حالت اب اضطراب کی سی ہے' },
    ],
  },
  {
    id: 3,
    poet_name_urdu: 'فیض احمد فیض',
    poet_name_english: 'Faiz Ahmed Faiz',
    title_urdu: 'مجھ سے پہلی سی محبت میری محبوب نہ مانگ',
    slug: 'mujh-se-pehli-si-mohabbat-faiz',
    type: 'nazm',
    views: 22100,
    is_featured: true,
    stanzas: [
      { misra_1: 'مجھ سے پہلی سی محبت میری محبوب نہ مانگ', misra_2: 'میں نے سمجھا تھا کہ تو ہے تو درخشاں ہے حیات' },
      { misra_1: 'تیرا غم ہے تو غمِ دہر کا جھگڑا کیا ہے', misra_2: 'تیری صورت سے ہے عالم میں بہاروں کو ثبات' },
      { misra_1: 'اور بھی دکھ ہیں زمانے میں محبت کے سوا', misra_2: 'راحتیں اور بھی ہیں وصل کی راحت کے سوا' },
    ],
  },
];
